### ISSUE TITLE
Heroic Games Launcher games launched through Steam on a gamescope session do not work

### ISSUE THREAD

**Issue by italoghost** [Open-Wine-Components/ULWGL#192]
I am not sure when this started to happen, but since last week I cannot launch any games from Heroic Games Launcher when using UMU (set on the advanced tab) when I am on the gamescope session (I use Arch Linux and installed a gamescope session through AUR).

If I disable the Umu option on Heroic, the games that created the shortcut to launch through Steam start just fine.

This option does not occur with the games that I installed through Lutris, that I launch through Steam and which I am using Umu as well, tho. 

I am using the latest git from Umu, Lutris and Heroic Games Launcher. If you need any logs, just tell me!

**Comment by R1kaB3rN** [comment]
If you're using the Heroic Games Launcher Flatpak on the Steam Deck then I am closing this because this problem was addressed a while ago. See https://github.com/Open-Wine-Components/umu-launcher/issues/92I

Now, it's up to HGL to update their built-in umu-launcher, and I invite you to ask for an ETA on this in their Discord channel.

**Comment by R1kaB3rN** [comment]
However, if you're not and believe it's a regression, then I'll need information to work with. 

First, please [replace Heroic's built in umu-launcher by following these steps](https://github.com/Open-Wine-Components/umu-launcher/issues/182#issuecomment-2345109091). In the instructions, just be sure to refer to Heroic's runtime directory instead of Lutris' and keep the `current_version` file if you see it so HGL doesn't restore everything. To make it easy for you, since you'll probably be doing this on the SD, I'll attach the reproducible executable below for you to use. Additionally, set `UMU_LOG=debug` and copy the traceback you see there from `$HOME/.local/share/Steam/logs/console-linux.txt`.

**Comment by R1kaB3rN** [comment]
[umu-run.gz](https://github.com/user-attachments/files/17092532/umu-run.gz)

**Comment by italoghost** [comment]
I am using Arch Linux! I have installed the latest git of Umu by changing the PKGBUILD of AUR package to it.

Heroic is compiled on its latest git as well (same as Lutris) through the AUR's "-git" package.

I really though that Heroic used the system wide binary for umu-launcher - I didn't know they were shipping an already built one. Tomorrow I will try to replace the umu-launcher runtime from Heroic and return the log file to you.

**Comment by R1kaB3rN** [comment]
Thanks for clarifying.

Yeah, HGL will prefer the system wide binary if it can find it. Otherwise, it will use its bundled one which is outdated -- umu-launcher 0.1-RC4.

**Comment by italoghost** [comment]
Hi! Heroic does not seem to have a bundled binary for umu-launcher. I couldn't find it on ~/.conf/heroic nor on /opt/heroic. 

Here are the logs. I first have launched it through Steam on the Gnome Session, which launched successfully. 

[console-linux_launched_gnome.txt](https://github.com/user-attachments/files/17105140/console-linux_launched_gnome.txt)

Then I launched it through the gamescope session, which just kept loading:

[console-linux_launched_gamescope_session.txt](https://github.com/user-attachments/files/17105143/console-linux_launched_gamescope_session.txt)

Edit: The game is Cat Quest II

**Comment by R1kaB3rN** [comment]
Those logs were not what I am looking for, but thanks for the effort.

A fix for this issue was addressed in the latest main branch, and I'm confident it should be solved. When you can make the time, please rebuild umu-launcher against the latest main branch and rerun your game in those conditions.

Feel free to reopen this issue if it still occurs, but I'll need to ask you to use reproducible builds, list precise steps to reproduce it, and to upload the logs that I am looking for. Concretely, these are HGL's logs in `$HOME/.config/heroic/GamesConfig` after setting `UMU_LOG=debug` and not using compiled git builds specific to your machine.

**Comment by italoghost** [comment]
Hi!

So, I recompiled `umu-launcher` with the latest git - I used the [AUR package](https://aur.archlinux.org/packages/umu-launcher) as a base and simply changed the line 64 from the PKGBUILD that defines from which commit it should build - and it is still not working.

I am using this package to run Heroic ([heroic-games-launcher-git](https://aur.archlinux.org/packages/heroic-games-launcher-git)). The gamescope related packages that I am using are these ones: [gamescope-session-sk-git](https://aur.archlinux.org/packages/gamescope-session-sk-git), [gamescope-session-steam-git](https://aur.archlinux.org/packages/gamescope-session-steam-git) and [gamescope-sk](https://aur.archlinux.org/packages/gamescope-sk).

I have installed my game - in this case, Cat Quest II - through Heroic and asked it to create a shortcut to Steam. Then, within the gamescope-session, I launched it, with a infinite loading.

Here is the logs from Heroic (`~/.config/heroic/GamesConfig`):

[1958338581-lastPlay_gamescope_session.log](https://github.com/user-attachments/files/17124115/1958338581-lastPlay_gamescope_session.log)
[1958338581_gamescope_session.json](https://github.com/user-attachments/files/17124116/1958338581_gamescope_session.json)

As you can see, It doesn't even properly enter the game.

Here is the log from Steam:

[console-linux_gamescope_session.txt](https://github.com/user-attachments/files/17124122/console-linux_gamescope_session.txt)

For comparison, here is the logs when the game successfully launches through the Steam on the Gnome session:

[1958338581-lastPlay.log](https://github.com/user-attachments/files/17124144/1958338581-lastPlay.log)
[1958338581.json](https://github.com/user-attachments/files/17124145/1958338581.json)

I know that you asked to use reproducible builds, but how can I change the `umu-launcher` that Heroic uses, as it doesn't seem to ship a build itself? With Lutris, as you stated in one of your comments, is possible to overwrite the one from the its runtime, but I do not know how I would be able to do that with Heroic. I would appreciate if you guided me!

**Comment by italoghost** [comment]
Just pointing out, I can't reopen the issue.

**Comment by R1kaB3rN** [comment]
Before we move forward and I take another look at this, do you mind supporting this statement by using a package of umu-launcher where it worked for that game in those same conditions:

> I am not sure when this started to happen, but since last week I cannot launch any games from Heroic Games Launcher when using UMU (set on the advanced tab) when I am on the gamescope session (I use Arch Linux and installed a gamescope session through AUR).

**Comment by italoghost** [comment]
Hi! I have tested a few commits and the last one that works is this one: https://github.com/Open-Wine-Components/umu-launcher/commit/2d3c948a51bc1d2880a90bf985947f9afc89e8d1

**Comment by italoghost** [comment]
It is fixed now! Probably it was fixed by this commit here: https://github.com/Open-Wine-Components/umu-launcher/commit/45b4ab260df1de02d35fb7db4ae49985ec3cfc63

**Comment by italoghost** [comment]
It is fixed now! Probably it was fixed by this commit here: https://github.com/Open-Wine-Components/umu-launcher/commit/45b4ab260df1de02d35fb7db4ae49985ec3cfc63
